version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: spendly_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LghycekmCyRprpKJMERfvxzBoHyuVzLH
      POSTGRES_DB: railway
    ports:
      - "55941:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spendly_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_TYPE: "postgres"
      DB_DSN: "postgresql://postgres:LghycekmCyRprpKJMERfvxzBoHyuVzLH@db:5432/railway?sslmode=disable"
      PORT: "8080"

volumes:
  postgres_data:
